server:
  port:  8080

# ES & rabbitmq
# virtual-host: rabbit_vhost
spring:
  data:
    elasticsearch:
      cluster-name: 118.31.239.157
  rabbitmq:
    host: 118.31.239.157
    port: 5672
    username: user
    password: FN9725
    virtual-host: rabbit_vhost
  redis:
    host: 118.31.239.157
    port: 6379
    password: founder@9725*FN
    timeout: 30
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500

# logbak
logging:
  config: classpath:logback-spring.xml

