server:
  port:  8086

# ES & rabbitmq
# virtual-host: rabbit_vhost
spring:
  data:
    elasticsearch:
      cluster-name: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: rabbit_vhost
  redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 30
      poolMaxTotal: 1000
      poolMaxIdle: 500
      poolMaxWait: 500

# logbak
logging:
  config: classpath:logback-spring.xml

