server:
  port:  8080

# ES & rabbitmq
# virtual-host: rabbit_vhost
spring:
  data:
    elasticsearch:
      cluster-name: 172.19.207.201
  rabbitmq:
    host: 172.19.207.201
    port: 5672
    username: admin
    password: admin
    virtual-host: rabbit_vhost

# logbak
logging:
  config: classpath:logback-spring.xml

# app config
app:
  config:
    identify: local
    queue: local_sitemonitor_queue



